server:
  port: 8001
mybatis:
#  config-location: classpath:mybatis/mybatisconfig.xml
#  type-aliases-package: org.example.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
#    对外暴露的微服务名字  很重要
    name: springcloudtest-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h5384h1ot9ztbrfo.mysql.rds.aliyuncs.com:3306/cloudb01?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: Hxx&Wyj_22-3-8@private
    dbcp2:
      min-idle: 5 #数据库最小链接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间


eureka:
  client:   #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    #修改实例id
    instance-id:  dept   #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示ip地址



info:
  app.name: springcloud-test
  author.name: wuyuejie
  build.artifactId: $project.artifactId$
  build.version: $project.version$