server:
  port: 7003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h5384h1ot9ztbrfo.mysql.rds.aliyuncs.com:3306/cloudb01?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: Hxx&Wyj_22-3-8@private

eureka:
  instance:
    hostname: eureka7003.com    #eureka服务端的实例名称
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #设置于eureka server交互的地址查询服务核和注册服务都需要依赖这个地址、