server:
  port: 9527

spring:
  application:
    name: springcloudtest-zuul-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h5384h1ot9ztbrfo.mysql.rds.aliyuncs.com:3306/cloudb01?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: Hxx&Wyj_22-3-8@private
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydeptx.serviceId: springcloudtest-dept
    mydeptx.path: /mydept/**
#    mydeptx自定义参数  serviId 与path是固定写法
  ignored-services: springcloudtest-dept
  prefix: /wyj
#  prefix添加访问前缀

info:
  app.name: springcloud-test
  author.name: wuyuejie
  build.artifactId: $project.artifactId$
  build.version: $project.version$70